name: NyaOne Docker Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ nya ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-thumbor:
    name: Build and publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        baseDist: [ 'alpine' ]
        versionMinor: [ '7.4' ]
        versionMajor: [ '7' ]

    steps:
      -
        name: Prepare env variables
        run: |
          echo "BUILD_DATE=$(TZ=':UTC' date +'%Y-%m-%d %H:%M:%S (%Z)')" >> ${GITHUB_ENV}
          echo "BUILD_INFO=${GITHUB_SHA::7}" >> ${GITHUB_ENV}

      -
        name: Check out code
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build images and push to registry
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          #cache-from: type=gha, scope=${{ github.workflow }}-${{ matrix.version }}-${{ matrix.baseDist }}
          #cache-to: type=gha, scope=${{ github.workflow }}-${{ matrix.version }}-${{ matrix.baseDist }}, mode=max
          context: .
          file: ./docker/thumbor-${{ matrix.versionMinor }}/Dockerfile-${{ matrix.baseDist }}
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_INFO=${{ env.BUILD_INFO }}
          tags: |
            nyaone/thumbor-s3:latest
            nyaone/thumbor-s3:${{ matrix.baseDist }}
            nyaone/thumbor-s3:${{ matrix.versionMinor }}-${{ matrix.baseDist }}
            nyaone/thumbor-s3:${{ matrix.versionMajor }}-${{ matrix.baseDist }}
          pull: true
          push: true

      - name: Send success webhook
        run: curl ${{ secrets.DOCKER_BUILD_SUCCESS_WEBHOOK }}?subject=thumbor%20%E9%95%9C%E5%83%8F

